# Generated by Django 4.0.6 on 2022-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girlsmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bar_photo'),
        ),
    ]
